# Generated by Django 5.1.1 on 2024-09-30 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_image/'),
        ),
        migrations.AddField(
            model_name='project',
            name='movie_type',
            field=models.CharField(default='Action', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
